general bash improvements
use single quotes where applicable
dont need to specify 1>&2
always do "${varible}" (with the braces)
in double quotes

diff --git a/mpv-get-property b/mpv-get-property
--- a/mpv-get-property
+++ b/mpv-get-property
@@ -4,8 +4,8 @@
 # all other arguments are sent to the socket using socat
 
 SOCKET="${1:?Must provide socket as first argument}"
-if [[ -e "$SOCKET" ]]; then
-	if [[ ! -S "$SOCKET" ]]; then
+if [[ -e "${SOCKET}" ]]; then
+	if [[ ! -S "${SOCKET}" ]]; then
 		echo "Path is not a socket: ${SOCKET}" >&2
 		exit 2
 	fi
@@ -17,10 +17,10 @@ PROPERTY="${2:?Must provide property as second argument}"
 readonly SOCKET PROPERTY
 
 # interpolate the property and capture the response
-MPV_RESP="$(socat - "$SOCKET" <<<"$(printf '{ "command": ["get_property", "%s" ] }' "$PROPERTY")")"
-err="$(echo "$MPV_RESP" | jq -r '.error')"
-[[ "$err" = "success" ]] || {
-	echo "Error: ${err}" 1>&2
+MPV_RESP="$(socat - "${SOCKET}" <<<"$(printf '{ "command": ["get_property", "%s" ] }' "${PROPERTY}")")"
+err="$(echo "${MPV_RESP}" | jq -r '.error')"
+[[ "${err}" = "success" ]] || {
+	echo "Error: ${err}" >&2
 	exit 1
 }
-echo "$MPV_RESP" | jq -r '.data'
+echo "${MPV_RESP}" | jq -r '.data'
diff --git a/mpv-play-pause b/mpv-play-pause
--- a/mpv-play-pause
+++ b/mpv-play-pause
@@ -17,29 +17,29 @@ toggle() {
 IFS=$'\n'
 # if something is playing, stop it and link it to /tmp/mpv-recently-paused
 if currently_playing=($(mpv-currently-playing --socket)); then
-	rm -f "$last_playing"
+	rm -f "${last_playing}"
 	# get the most recently launched currently playing mpv instance
 	most_recent="${currently_playing[-1]}"
 	echo "Pausing ${most_recent}..."
-	toggle "$most_recent" || exit $?
-	ln -s "$most_recent" "$last_playing"
+	toggle "${most_recent}" || exit $?
+	ln -s "${most_recent}" "${last_playing}"
 else
 	# nothing is playing, try to start '/tmp/mpv-recently-paused' if that mpv instance is still active
-	if toggle "$last_playing"; then
-		echo "Found recently paused socket, resuming..."
+	if toggle "${last_playing}"; then
+		echo 'Found recently paused socket, resuming...'
 	else
 		echo "Couldn't start a recently paused socket..." >&2
-		echo "Starting the most recent mpv instance, if one exists..."
+		echo 'Starting the most recent mpv instance, if one exists...'
 		if all_sockets=($(mpv-active-sockets)); then
 			most_recent="${all_sockets[-1]}"
-			if toggle "$most_recent"; then
-				echo "Success!"
+			if toggle "${most_recent}"; then
+				echo 'Success!'
 			else
-				echo "Failed..." >&2
+				echo 'Failed...' >&2
 				exit 1
 			fi
 		else
-			echo "No active mpv instances... exiting" >&2
+			echo 'No active mpv instances... exiting' >&2
 			exit 1
 		fi
 	fi
diff --git a/mpv-quit-pick b/mpv-quit-pick
--- a/mpv-quit-pick
+++ b/mpv-quit-pick
@@ -3,7 +3,7 @@
 # and send it a 'quit' command
 
 abort() {
-	echo "$1" 1>&2
+	echo "$1" >&2
 	exit 1
 }
 
@@ -13,15 +13,15 @@ declare chosen
 if active=($(mpv-active-sockets)); then
 	chosen="$({
 		for socket in "${active[@]}"; do
-			printf "%s:" "$socket"
-			mpv-get-property "$socket" 'path' || exit $?
+			printf '%s:' "${socket}"
+			mpv-get-property "${socket}" 'path' || exit $?
 		done
-	} | fzf +m -i --prompt="Select mpv instance to quit > ")" || abort "No instance selected..."
+	} | fzf +m -i --prompt='Select mpv instance to quit > ')" || abort 'No instance selected...'
 	if [[ -n "${chosen}" ]]; then
 		exec mpv-communicate "${chosen%%:*}" 'quit'
 	else
-		abort "Error getting selected instance..."
+		abort 'Error getting selected instance...'
 	fi
 else
-	abort "No active mpv instances..."
+	abort 'No active mpv instances...'
 fi
