mpv-get-property; update error handling

diff --git a/mpv-get-property b/mpv-get-property
--- a/mpv-get-property
+++ b/mpv-get-property
@@ -20,15 +20,14 @@ readonly SOCKET PROPERTY
 MPV_RESP="$(printf '{ "command": ["get_property", "%s" ] }\n' "${PROPERTY}" | socat - "${SOCKET}")"
 
 # to reduce overhead from multiple jq calls -- try the common case first
-# filter and extract data from success if it worked
+# select (filter) and extract data if it succeeded
 DATA="$(jq -r 'select(.error == "success") | .data' <<<"$MPV_RESP")"
 if [[ -z "$DATA" ]]; then
-	# was empty, so extract error
+	# was empty, so extract/dump error
 	err="$(echo "${MPV_RESP}" | jq -r '.error')"
-	if [[ "err" != "success" ]]; then
-		echo "Error: ${err}" >&2
-		exit 1
-	fi
+	echo -e "Error: ${err}\nResponse:" >&2
+	jq <<<"${MPV_RESP}" >&2
+	exit 1
 fi
 # data wasn't empty; succeeded
 echo "${DATA}"
